### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by EvilLord666** [EvilLord666/ReportGeneratorWebGui#22]
Mysql timeout not passing/passing wrongly into ReportGenerator when attempt to execute procedure that returns more then `~5M lines and 85 secs` (according to MySql Workbench) from stored procedure:
```
An error occured during read data impl async, exception: MySql.Data.MySqlClient.MySqlException (0x80004005): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
       ---> System.TimeoutException: Timeout in IO operation
         at MySql.Data.MySqlClient.TimedStream.StopTimer()
         at MySql.Data.MySqlClient.TimedStream.Read(Byte[] buffer, Int32 offset, Int32 count)
         at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer, Int32 offset, Int32 count)
         at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
         at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
         at MySql.Data.MySqlClient.NativeDriver.FetchDataRow(Int32 statementId, Int32 columns)
         at MySql.Data.MySqlClient.ResultSet.GetNextRow()
         at MySql.Data.MySqlClient.ResultSet.NextRow(CommandBehavior behavior)
         at MySql.Data.MySqlClient.MySqlDataReader.Read()
         at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
         at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
         at MySql.Data.MySqlClient.MySqlConnection.HandleTimeoutOrThreadAbort(Exception ex)
         at MySql.Data.MySqlClient.MySqlDataReader.Read()
         at System.Data.Common.DbDataReader.ReadAsync(CancellationToken cancellationToken)
      --- End of stack trace from previous location where exception was thrown ---
         at ReportGenerator.Core.Extractor.SimpleDbExtractor.ReadDataImplAsync(DbCommand command)
```

**Comment by EvilLord666** [comment]
With less amount (~1.3M works fine)

**Comment by EvilLord666** [comment]
We could pass timeout in Mysql like that:
`Server=myServerAddress;Database=myDataBase;Uid=myUsername;Pwd=myPassword;
default command timeout=600;`

**Comment by EvilLord666** [comment]
According to this image report was successfully generated ~1Gb with 17 Million lines
![image](https://user-images.githubusercontent.com/18068522/172659553-b75262e4-0393-4fdf-be07-3dd19148362c.png)

**Comment by EvilLord666** [comment]
there is no problem with timeout, we should pass proper connection string
